import { randomBytes } from 'crypto';
import path from 'path';

/**
 * Object key generation and validation.
 *
 * Keys are ALWAYS generated by the server and never contain customer names,
 * phone numbers, emails or credentials:
 *
 *   chat/{objectId}/{versionId}
 *   assistant/{objectId}/{versionId}
 *   documents/{objectId}/{versionId}
 *   recordings/{callId}/{recordingId}
 *   quarantine/{objectId}/{versionId}
 */

export type StoragePurpose =
  | 'chat'
  | 'ai_attachment'
  | 'ai_artifact'
  | 'document'
  | 'recording'
  | 'transcript'
  | 'plugin'
  | 'knowledge'
  | 'comm_media'
  | 'export';

export const STORAGE_PURPOSES: StoragePurpose[] = [
  'chat',
  'ai_attachment',
  'ai_artifact',
  'document',
  'recording',
  'transcript',
  'plugin',
  'knowledge',
  'comm_media',
  'export',
];

const PREFIX_BY_PURPOSE: Record<StoragePurpose, string> = {
  chat: 'chat',
  ai_attachment: 'assistant',
  ai_artifact: 'assistant',
  document: 'documents',
  recording: 'recordings',
  transcript: 'transcripts',
  plugin: 'plugins',
  knowledge: 'knowledge',
  comm_media: 'comm',
  export: 'exports',
};

const SAFE_SEGMENT = /^[A-Za-z0-9_-]+$/;
const SAFE_KEY = /^[A-Za-z0-9_\-./]+$/;

export function newVersionId(): string {
  return randomBytes(9).toString('base64url');
}

export function assertSafeSegment(segment: string, label = 'segment'): void {
  if (!SAFE_SEGMENT.test(segment)) {
    throw new Error(`Invalid storage key ${label}`);
  }
}

/** A key is safe when it has no traversal, no leading slash and only plain characters. */
export function isSafeKey(key: string): boolean {
  if (!SAFE_KEY.test(key)) return false;
  if (key.startsWith('/') || key.includes('//')) return false;
  const parts = key.split('/');
  return parts.every((p) => p.length > 0 && p !== '.' && p !== '..');
}

export function assertSafeKey(key: string): void {
  if (!isSafeKey(key)) {
    throw new Error('Invalid storage key');
  }
}

export function buildObjectKey(
  purpose: StoragePurpose,
  objectId: string,
  versionId: string
): string {
  assertSafeSegment(objectId, 'objectId');
  assertSafeSegment(versionId, 'versionId');
  return `${PREFIX_BY_PURPOSE[purpose]}/${objectId}/${versionId}`;
}

export function buildQuarantineKey(objectId: string, versionId: string): string {
  assertSafeSegment(objectId, 'objectId');
  assertSafeSegment(versionId, 'versionId');
  return `quarantine/${objectId}/${versionId}`;
}

export function buildRecordingKey(callId: string, recordingId: string): string {
  assertSafeSegment(callId, 'callId');
  assertSafeSegment(recordingId, 'recordingId');
  return `recordings/${callId}/${recordingId}`;
}

/** Legacy directories that migrated/legacy reads are allowed to touch. */
export const LEGACY_DIRECTORIES = [
  path.join('data', 'chat-attachments'),
  path.join('data', 'ai-attachments'),
  path.join('data', 'ai-artifacts'),
] as const;

/**
 * Returns true when an absolute or relative legacy path resolves INSIDE one of
 * the allowed legacy directories. Used before reading any legacy `storagePath`
 * coming from the database — a manipulated value must never escape.
 */
export function isLegacyPathAllowed(storagePath: string, cwd: string = process.cwd()): boolean {
  if (!storagePath || storagePath.includes('\0')) return false;
  const resolved = path.resolve(cwd, storagePath);
  return LEGACY_DIRECTORIES.some((dir) => {
    const base = path.resolve(cwd, dir);
    return resolved === base || resolved.startsWith(base + path.sep);
  });
}
