import { prisma } from '@/lib/prisma';
import { Prisma } from '@prisma/client';
import { deleteObjectIfUnreferenced } from '@/modules/storage/storage-service';
import { isLegacyPathAllowed } from '@/modules/storage/storage-keys';

/**
 * AI Artifact Service
 *
 * Manages creation, storage, retrieval, and cleanup of artifacts
 * (PDF, Excel, CSV, tables, charts) generated by the AI assistant.
 *
 * Artifacts are stored in two ways:
 * - Binary files (PDF, XLSX, CSV): stored in the object storage (R2 in
 *   production) and referenced through `storageObjectId`. Rows created before
 *   the migration keep a legacy `storagePath` under /data/ai-artifacts/.
 * - Inline data (tables, charts as JSON/SVG): stored in AiArtifact.inlineData
 *
 * Each artifact has a TTL (configurable, default 7 days) and is cleaned up
 * automatically — except artifacts marked as approved/shared
 * (`meta.protected = true`), which the generic cleanup never touches.
 */

type ArtifactType = 'pdf' | 'xlsx' | 'csv' | 'table' | 'chart' | 'image';

interface ArtifactMeta {
  title: string;
  description?: string;
  filename?: string;
  mimeType?: string;
  sizeBytes?: number;
  columns?: string[];
  rowCount?: number;
  chartType?: string;
  customColors?: string[];
  logoUrl?: string;
  brandColor?: string;
  subtitle?: string;
  author?: string;
  pageCount?: number;
  labels?: string[];
  seriesCount?: number;
  [key: string]: unknown;
}

interface CreateArtifactInput {
  conversationId: string;
  messageId?: string;
  type: ArtifactType;
  /** Legacy only. New artifacts use storageObjectId. */
  storagePath?: string;
  storageObjectId?: string;
  inlineData?: Prisma.InputJsonValue;
  meta: ArtifactMeta;
}

/**
 * Creates a new artifact record in the database.
 */
export async function createArtifact(input: CreateArtifactInput) {
  return prisma.aiArtifact.create({
    data: {
      conversationId: input.conversationId,
      messageId: input.messageId ?? null,
      type: input.type,
      storagePath: input.storagePath ?? null,
      storageObjectId: input.storageObjectId ?? null,
      inlineData: input.inlineData ?? Prisma.JsonNull,
      meta: input.meta as unknown as Prisma.InputJsonValue,
    },
  });
}

/**
 * Retrieves an artifact by ID.
 */
export async function getArtifact(id: string) {
  return prisma.aiArtifact.findUnique({ where: { id } });
}

/**
 * Lists artifacts for a conversation, newest first.
 */
export async function listArtifacts(conversationId: string) {
  return prisma.aiArtifact.findMany({
    where: { conversationId },
    orderBy: { createdAt: 'desc' },
  });
}

/**
 * Deletes an artifact and its file (if on disk).
 */
export async function deleteArtifact(id: string): Promise<void> {
  const artifact = await prisma.aiArtifact.findUnique({ where: { id } });
  if (!artifact) return;
  await prisma.aiArtifact.delete({ where: { id } });
  await releaseArtifactFile(artifact);
}

/** Releases the binary of an artifact row that has already been deleted. */
async function releaseArtifactFile(artifact: { storagePath: string | null; storageObjectId: string | null }): Promise<void> {
  if (artifact.storageObjectId) {
    await deleteObjectIfUnreferenced(artifact.storageObjectId);
    return;
  }
  if (artifact.storagePath && isLegacyPathAllowed(artifact.storagePath)) {
    const fs = await import('fs/promises');
    try {
      await fs.unlink(artifact.storagePath);
    } catch {
      // file may already be gone
    }
  }
}

function isProtected(meta: unknown): boolean {
  return Boolean(meta && typeof meta === 'object' && (meta as Record<string, unknown>).protected === true);
}

/** Marks an artifact as approved/shared: excluded from the generic cleanup. */
export async function protectArtifact(id: string, protectedFlag = true): Promise<void> {
  const artifact = await prisma.aiArtifact.findUnique({ where: { id } });
  if (!artifact) return;
  const meta = { ...((artifact.meta as Record<string, unknown> | null) ?? {}), protected: protectedFlag };
  await prisma.aiArtifact.update({ where: { id }, data: { meta: meta as Prisma.InputJsonValue } });
  if (artifact.storageObjectId) {
    await prisma.storageObject.update({
      where: { id: artifact.storageObjectId },
      data: { retentionPolicy: protectedFlag ? 'protected' : 'default' },
    });
  }
}

/**
 * Cleans up artifacts older than the TTL (in hours).
 * Returns the number of artifacts deleted.
 */
export async function cleanupExpiredArtifacts(ttlHours: number): Promise<number> {
  const cutoff = new Date(Date.now() - ttlHours * 60 * 60 * 1000);
  const candidates = await prisma.aiArtifact.findMany({
    where: { createdAt: { lt: cutoff } },
    select: { id: true, storagePath: true, storageObjectId: true, meta: true },
  });
  const expired = candidates.filter((a) => !isProtected(a.meta));
  if (expired.length === 0) return 0;
  const result = await prisma.aiArtifact.deleteMany({
    where: { id: { in: expired.map((a) => a.id) } },
  });
  for (const artifact of expired) {
    await releaseArtifactFile(artifact);
  }
  return result.count;
}

/**
 * Sanitizes an artifact for API response (strips storagePath for security).
 */
export function sanitizeArtifact(artifact: {
  id: string;
  conversationId: string;
  messageId: string | null;
  type: string;
  storagePath: string | null;
  storageObjectId?: string | null;
  inlineData: unknown;
  meta: unknown;
  createdAt: Date;
}) {
  return {
    id: artifact.id,
    conversationId: artifact.conversationId,
    messageId: artifact.messageId,
    type: artifact.type,
    hasFile: Boolean(artifact.storagePath || artifact.storageObjectId),
    inlineData: artifact.inlineData,
    meta: artifact.meta,
    createdAt: artifact.createdAt.toISOString(),
  };
}
