/**
 * Central column registry for the Sales Orders workspace.
 *
 * Every column that can appear in the table is defined here. The UI reads
 * this registry to build column definitions, the filter builder, the column
 * manager, and exports. Never define columns ad-hoc in components.
 */

export type SalesOrderColumnType = 'text' | 'date' | 'number' | 'currency' | 'status' | 'boolean';

export type SalesOrderColumnAlign = 'left' | 'right' | 'center';

export interface SalesOrderColumnDefinition {
  id: string;
  label: string;
  /** Prisma field key used for sorting and filtering. */
  field: string;
  type: SalesOrderColumnType;
  sortable: boolean;
  filterable: boolean;
  defaultVisible: boolean;
  defaultWidth: number;
  minWidth: number;
  maxWidth: number;
  align: SalesOrderColumnAlign;
  /** Lower = higher priority. Used for default ordering and mobile compact. */
  priority: number;
  /** Optional formatter key for client-side rendering. */
  formatter?: 'date' | 'currency' | 'statusDot' | 'boolean';
  /** Optional status category for label/tone mapping. */
  statusCategory?: 'order' | 'payment' | 'invoice' | 'shipping' | 'sub_status' | 'ticket';
}

export const SALES_ORDERS_TABLE_KEY = 'sales_orders';

export const SALES_ORDER_COLUMNS: SalesOrderColumnDefinition[] = [
  {
    id: 'orderDate',
    label: 'Fecha',
    field: 'orderDate',
    type: 'date',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'left',
    priority: 1,
    formatter: 'date',
  },
  {
    id: 'salesOrderNumber',
    label: 'Orden',
    field: 'salesOrderNumber',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 180,
    align: 'left',
    priority: 2,
  },
  {
    id: 'referenceNumber',
    label: 'Referencia',
    field: 'referenceNumber',
    type: 'text',
    sortable: false,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 180,
    align: 'left',
    priority: 3,
  },
  {
    id: 'customerName',
    label: 'Cliente',
    field: 'customerName',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 220,
    minWidth: 120,
    maxWidth: 360,
    align: 'left',
    priority: 4,
  },
  {
    id: 'status',
    label: 'Estado',
    field: 'status',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 180,
    align: 'left',
    priority: 5,
    formatter: 'statusDot',
    statusCategory: 'order',
  },
  {
    id: 'ticketStatus',
    label: 'Ticket',
    field: 'ticketStatus',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 140,
    minWidth: 100,
    maxWidth: 180,
    align: 'left',
    priority: 5.5,
    formatter: 'statusDot',
    statusCategory: 'ticket',
  },
  {
    id: 'subStatus',
    label: 'Sub-estado',
    field: 'subStatus',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 180,
    align: 'left',
    priority: 5.6,
    formatter: 'statusDot',
    statusCategory: 'sub_status',
  },
  {
    id: 'invoicedStatus',
    label: 'Facturada',
    field: 'invoicedStatus',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'left',
    priority: 6,
    formatter: 'statusDot',
    statusCategory: 'invoice',
  },
  {
    id: 'paidStatus',
    label: 'Pago',
    field: 'paidStatus',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'left',
    priority: 7,
    formatter: 'statusDot',
    statusCategory: 'payment',
  },
  {
    id: 'shippedStatus',
    label: 'Envío',
    field: 'shippedStatus',
    type: 'status',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'left',
    priority: 8,
    formatter: 'statusDot',
    statusCategory: 'shipping',
  },
  {
    id: 'total',
    label: 'Total',
    field: 'total',
    type: 'currency',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 180,
    align: 'right',
    priority: 9,
    formatter: 'currency',
  },
  {
    id: 'deliveryMethod',
    label: 'Entrega',
    field: 'deliveryMethod',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: true,
    defaultWidth: 140,
    minWidth: 110,
    maxWidth: 220,
    align: 'left',
    priority: 10,
  },
  {
    id: 'carrier',
    label: 'Transportista',
    field: 'carrier',
    type: 'text',
    sortable: false,
    filterable: false,
    defaultVisible: true,
    defaultWidth: 140,
    minWidth: 100,
    maxWidth: 200,
    align: 'left',
    priority: 10.5,
  },
  {
    id: 'salespersonName',
    label: 'Vendedor',
    field: 'salespersonName',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 150,
    minWidth: 110,
    maxWidth: 220,
    align: 'left',
    priority: 11,
  },
  {
    id: 'customerPhone',
    label: 'Teléfono',
    field: 'customerPhone',
    type: 'text',
    sortable: false,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 180,
    align: 'left',
    priority: 12,
  },
  {
    id: 'paymentMethod',
    label: 'Forma de pago',
    field: 'paymentMethod',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 200,
    align: 'left',
    priority: 13,
  },
  {
    id: 'locationName',
    label: 'Ubicación',
    field: 'locationName',
    type: 'text',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 200,
    align: 'left',
    priority: 14,
  },
  {
    id: 'branchName',
    label: 'Sucursal',
    field: 'branchName',
    type: 'text',
    sortable: false,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 180,
    align: 'left',
    priority: 15,
  },
  {
    id: 'subtotal',
    label: 'Subtotal',
    field: 'subtotal',
    type: 'currency',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 180,
    align: 'right',
    priority: 16,
    formatter: 'currency',
  },
  {
    id: 'discountTotal',
    label: 'Descuento',
    field: 'discountTotal',
    type: 'currency',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'right',
    priority: 17,
    formatter: 'currency',
  },
  {
    id: 'taxTotal',
    label: 'Impuestos',
    field: 'taxTotal',
    type: 'currency',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
    maxWidth: 160,
    align: 'right',
    priority: 18,
    formatter: 'currency',
  },
  {
    id: 'shippingCharge',
    label: 'Envío',
    field: 'shippingCharge',
    type: 'currency',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 140,
    align: 'right',
    priority: 19,
    formatter: 'currency',
  },
  {
    id: 'adjustment',
    label: 'Ajuste',
    field: 'adjustment',
    type: 'currency',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 140,
    align: 'right',
    priority: 20,
    formatter: 'currency',
  },
  {
    id: 'balance',
    label: 'Saldo',
    field: 'balance',
    type: 'currency',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 170,
    align: 'right',
    priority: 21,
    formatter: 'currency',
  },
  {
    id: 'currencyCode',
    label: 'Moneda',
    field: 'currencyCode',
    type: 'text',
    sortable: false,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 90,
    minWidth: 70,
    maxWidth: 120,
    align: 'center',
    priority: 22,
  },
  {
    id: 'saleMadeInWarehouse',
    label: 'Venta en almacén',
    field: 'saleMadeInWarehouse',
    type: 'boolean',
    sortable: false,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
    maxWidth: 180,
    align: 'center',
    priority: 23,
    formatter: 'boolean',
  },
  {
    id: 'sourceRemoteModifiedAt',
    label: 'Última modificación remota',
    field: 'sourceRemoteModifiedAt',
    type: 'date',
    sortable: true,
    filterable: true,
    defaultVisible: false,
    defaultWidth: 170,
    minWidth: 130,
    maxWidth: 220,
    align: 'left',
    priority: 24,
    formatter: 'date',
  },
  {
    id: 'shippingAddress',
    label: 'Dirección de envío',
    field: 'shippingAddress',
    type: 'text',
    sortable: false,
    filterable: false,
    defaultVisible: false,
    defaultWidth: 240,
    minWidth: 120,
    maxWidth: 400,
    align: 'left',
    priority: 25,
  },
];

export const SALES_ORDER_COLUMN_MAP: Record<string, SalesOrderColumnDefinition> =
  Object.fromEntries(SALES_ORDER_COLUMNS.map((c) => [c.id, c]));

export const SALES_ORDER_DEFAULT_COLUMN_ORDER: string[] = SALES_ORDER_COLUMNS.sort(
  (a, b) => a.priority - b.priority
).map((c) => c.id);

export const SALES_ORDER_SORTABLE_FIELDS = new Set(
  SALES_ORDER_COLUMNS.filter((c) => c.sortable).map((c) => c.field)
);

export const SALES_ORDER_FILTERABLE_FIELDS = new Set(
  SALES_ORDER_COLUMNS.filter((c) => c.filterable).map((c) => c.field)
);
