import type { ProcessBlueprint, StepDef, StepEscalation } from './types';

/**
 * Blueprint `sales_fulfillment@1` (plan section 2.3, table of 15 steps).
 *
 * Published definitions are immutable: `registry.ts` stores this object with
 * its checksum in `ProcessVersion` and refuses a different definition under
 * the same version. Any change to a step (area, kind, dependencies, SLA,
 * conditions...) requires a new blueprint version.
 *
 * Exit event types keep the vocabulary of the plan table. `request.sent`
 * corresponds to the core event `request.created` emitted when the engine
 * creates the area request.
 *
 * Pure module.
 */

export const SALES_FULFILLMENT_PROCESS_KEY = 'sales_fulfillment';
export const SALES_FULFILLMENT_VERSION = 1;

/** Default escalation ladder of every step (same as `IntegrationConfig('operations')`). */
const ESCALATION: StepEscalation = {
  afterMinutes: [0, 120, 480],
  ladder: ['backup', 'area_lead', 'administracion'],
};

const DAY = 1440;

const STEPS: StepDef[] = [
  {
    key: 'verificar_disponibilidad',
    label: 'Verificar disponibilidad',
    areaKey: 'inventario',
    kind: 'verification',
    scope: 'demand',
    dependsOn: [],
    exit: { evidence: ['availability_result'], eventType: 'demand.verified' },
    slaMinutes: 120,
    ownerResolution: { area: 'inventario', byLocation: true },
    escalation: ESCALATION,
    autoComplete: 'controlledStockSufficient',
    completion: 'manual',
    uiAction: 'count_stock',
    phase: 'planning',
  },
  {
    key: 'plan_abastecimiento',
    label: 'Aprobar plan de abastecimiento',
    areaKey: 'ventas',
    kind: 'approval',
    scope: 'demand',
    dependsOn: ['verificar_disponibilidad'],
    exit: { evidence: ['allocation_plan'], eventType: 'demand.allocated' },
    slaMinutes: 240,
    ownerResolution: { role: 'case_owner' },
    escalation: ESCALATION,
    autoComplete: 'planCoveredByControlledStock',
    completion: 'manual',
    uiAction: 'plan_allocations',
    phase: 'planning',
  },
  {
    key: 'reservar_stock',
    label: 'Reservar existencia',
    areaKey: 'inventario',
    kind: 'action',
    scope: 'allocation',
    appliesTo: ['stock'],
    dependsOn: ['plan_abastecimiento'],
    exit: { evidence: ['stock_reservation'], eventType: 'stock.reserved' },
    slaMinutes: 15,
    ownerResolution: { area: 'inventario' },
    escalation: ESCALATION,
    autoComplete: 'allocationReserved',
    engine: 'reserve_stock',
    completion: 'condition',
    uiAction: 'reserve_stock',
    phase: 'sourcing',
  },
  {
    key: 'solicitar_compra',
    label: 'Solicitar compra',
    areaKey: 'compras',
    kind: 'action',
    scope: 'allocation',
    appliesTo: ['purchase'],
    dependsOn: ['plan_abastecimiento'],
    exit: { evidence: ['purchase_request_ref'], eventType: 'request.sent' },
    slaMinutes: 240,
    ownerResolution: { area: 'compras' },
    escalation: ESCALATION,
    autoComplete: 'allocationRequested',
    engine: 'request_purchase',
    completion: 'condition',
    phase: 'sourcing',
  },
  {
    key: 'esperar_recepcion',
    label: 'Esperar recepción de la compra',
    areaKey: 'compras',
    kind: 'wait',
    scope: 'allocation',
    appliesTo: ['purchase'],
    dependsOn: ['solicitar_compra'],
    exit: { evidence: ['receipt_movement'], eventType: 'stock.received' },
    slaMinutes: DAY,
    slaAnchor: 'expectedAt',
    slaFallbackMinutes: 7 * DAY,
    ownerResolution: { area: 'compras' },
    escalation: ESCALATION,
    autoComplete: 'allocationReady',
    completion: 'manual',
    phase: 'sourcing',
  },
  {
    key: 'ordenar_produccion',
    label: 'Ordenar producción',
    areaKey: 'manufactura',
    kind: 'action',
    scope: 'allocation',
    appliesTo: ['manufacture'],
    dependsOn: ['plan_abastecimiento'],
    exit: { evidence: ['production_order_ref'], eventType: 'request.sent' },
    slaMinutes: 240,
    ownerResolution: { area: 'manufactura' },
    escalation: ESCALATION,
    autoComplete: 'allocationRequested',
    engine: 'request_production',
    completion: 'condition',
    phase: 'sourcing',
  },
  {
    key: 'esperar_produccion',
    label: 'Esperar producción',
    areaKey: 'manufactura',
    kind: 'wait',
    scope: 'allocation',
    appliesTo: ['manufacture'],
    dependsOn: ['ordenar_produccion'],
    exit: { evidence: ['produce_movement'], eventType: 'production.finished' },
    slaMinutes: DAY,
    slaAnchor: 'expectedAt',
    slaFallbackMinutes: 5 * DAY,
    ownerResolution: { area: 'manufactura' },
    escalation: ESCALATION,
    autoComplete: 'allocationReady',
    completion: 'manual',
    phase: 'sourcing',
  },
  {
    key: 'coordinar_entrega_directa',
    label: 'Coordinar entrega directa del proveedor',
    areaKey: 'compras',
    kind: 'action',
    scope: 'allocation',
    appliesTo: ['direct_supplier'],
    dependsOn: ['plan_abastecimiento'],
    exit: { evidence: ['supplier_confirmation'], eventType: 'request.sent' },
    slaMinutes: 240,
    ownerResolution: { area: 'compras' },
    escalation: ESCALATION,
    autoComplete: 'allocationRequested',
    engine: 'request_direct_delivery',
    completion: 'condition',
    phase: 'sourcing',
  },
  {
    key: 'confirmar_entrega_directa',
    label: 'Confirmar entrega directa',
    areaKey: 'logistica',
    kind: 'verification',
    scope: 'allocation',
    appliesTo: ['direct_supplier'],
    dependsOn: ['coordinar_entrega_directa'],
    exit: { evidence: ['delivery_evidence'], eventType: 'delivery.confirmed' },
    slaMinutes: DAY,
    slaAnchor: 'expectedAt',
    slaFallbackMinutes: 7 * DAY,
    ownerResolution: { area: 'logistica' },
    escalation: ESCALATION,
    autoComplete: 'directDeliveryConfirmed',
    completion: 'manual',
    uiAction: 'record_delivery',
    phase: 'delivering',
  },
  {
    key: 'preparar_pedido',
    label: 'Preparar pedido',
    areaKey: 'inventario',
    kind: 'action',
    scope: 'case',
    dependsOn: ['reservar_stock', 'esperar_recepcion', 'esperar_produccion'],
    entryCondition: 'hasWarehouseAllocations',
    exit: { evidence: ['issue_movements'], eventType: 'order.prepared' },
    slaMinutes: 480,
    ownerResolution: { area: 'inventario' },
    escalation: ESCALATION,
    completion: 'manual',
    uiAction: 'prepare_order',
    phase: 'preparing',
  },
  {
    key: 'planear_entrega',
    label: 'Planear entrega',
    areaKey: 'logistica',
    kind: 'action',
    scope: 'case',
    dependsOn: ['preparar_pedido'],
    entryCondition: 'hasWarehouseAllocations',
    exit: { evidence: ['delivery_order'], eventType: 'delivery.planned' },
    slaMinutes: 240,
    ownerResolution: { area: 'logistica' },
    escalation: ESCALATION,
    autoComplete: 'deliveryPlanned',
    engine: 'plan_delivery',
    completion: 'condition',
    phase: 'delivering',
  },
  {
    key: 'asignar_transporte',
    label: 'Asignar transporte',
    areaKey: 'logistica',
    kind: 'external_sync',
    scope: 'case',
    dependsOn: ['planear_entrega'],
    entryCondition: 'requiresTransport',
    exit: { evidence: ['zoho_readback'], eventType: 'zoho.shipment_confirmed' },
    slaMinutes: 60,
    ownerResolution: { area: 'logistica' },
    escalation: ESCALATION,
    autoComplete: 'transportConfirmed',
    completion: 'condition',
    uiAction: 'assign_transport',
    phase: 'delivering',
  },
  {
    key: 'entregar',
    label: 'Entregar al cliente',
    areaKey: 'logistica',
    kind: 'action',
    scope: 'case',
    dependsOn: ['asignar_transporte'],
    entryCondition: 'hasWarehouseAllocations',
    exit: {
      evidence: ['delivery_evidence'],
      eventType: 'delivery.confirmed',
      alternateEventTypes: ['delivery.partial'],
    },
    slaMinutes: DAY,
    slaAnchor: 'plannedDate',
    slaFallbackMinutes: 2 * DAY,
    ownerResolution: { area: 'logistica' },
    escalation: ESCALATION,
    autoComplete: 'deliveriesClosed',
    completion: 'condition',
    uiAction: 'record_delivery',
    phase: 'delivering',
  },
  {
    key: 'cierre_operativo',
    label: 'Cierre operativo',
    areaKey: 'ventas',
    kind: 'verification',
    scope: 'case',
    dependsOn: ['entregar', 'confirmar_entrega_directa'],
    exit: { evidence: [], eventType: 'case.operational_closed' },
    slaMinutes: DAY,
    ownerResolution: { area: 'ventas' },
    escalation: ESCALATION,
    autoComplete: 'allDemandsFulfilled',
    completion: 'manual',
    uiAction: 'close_case',
    phase: 'closing',
  },
  {
    key: 'cierre_financiero',
    label: 'Cierre financiero',
    areaKey: 'contabilidad',
    kind: 'wait',
    scope: 'case',
    dependsOn: ['cierre_operativo'],
    exit: { evidence: [], eventType: 'case.financial_closed' },
    slaMinutes: 30 * DAY,
    ownerResolution: { area: 'contabilidad' },
    escalation: ESCALATION,
    autoComplete: 'salesOrderInvoicedAndPaid',
    completion: 'manual',
    phase: 'closing',
  },
];

export const SALES_FULFILLMENT_BLUEPRINT: ProcessBlueprint = {
  processKey: SALES_FULFILLMENT_PROCESS_KEY,
  version: SALES_FULFILLMENT_VERSION,
  label: 'Surtido de orden de venta',
  steps: STEPS,
};

/** Step keys of `sales_fulfillment` (the engine refers to them by name). */
export const SALES_STEP = {
  verify: 'verificar_disponibilidad',
  plan: 'plan_abastecimiento',
  reserve: 'reservar_stock',
  requestPurchase: 'solicitar_compra',
  awaitReceipt: 'esperar_recepcion',
  orderProduction: 'ordenar_produccion',
  awaitProduction: 'esperar_produccion',
  coordinateDirect: 'coordinar_entrega_directa',
  confirmDirect: 'confirmar_entrega_directa',
  prepare: 'preparar_pedido',
  planDelivery: 'planear_entrega',
  assignTransport: 'asignar_transporte',
  deliver: 'entregar',
  operationalClose: 'cierre_operativo',
  financialClose: 'cierre_financiero',
} as const;
